fullnameOverride: asd
# URL of Codefresh platform
codefreshURL: "https://g.codefresh.io"
# Tunnel server deployment
server:
  image:
    repository: quay.io/codefresh/frps
    pullPolicy: IfNotPresent
    tag: "2022.09.07-2158253"
  resources: {}

plugin:
  image:
    repository: gcr.io/codefresh-inc/codefresh-io/frp-codefresh-plugin
    pullPolicy: IfNotPresent
    tag: "ilia-medvedev-codefresh-patch-1-5e95b11"
  resources: {}

ingresses:
  # Subdomain ingress
  tunnels:
    subdomainHost: # Will be created in the form *.subdomain
    ingressClassName: ""
    ingressAnnotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    tls:
      enabled: false
      secretName:

  # Endpoint for tunnel registration
  clientRegistration:
    host:
    ingressClassName: ""
    ingressAnnotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    tls:
      enabled: false
      secretName:

serviceAccount:
  create: true
  annotations: {}
  name: "codefresh-tunnel-server"

imagePullSecrets: []
nodeSelector: {}
tolerations: []
affinity: {}
resources: {}
podSecurityContext: {}
podAnnotations: {}
  
# For scaling of the tunnel server set scaling to true. This requires the router component to be created
scaling:
  enabled: true
  # Redis parameters.
  
  redisURL: # String or map
    url:
    # Or secret key ref
    secretKeyRef:
      name:
      key:

  replicaCount: 2

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80

  router:
    image:
      repository: gcr.io/codefresh-inc/codefresh-io/frp-router
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: ""
    
    serviceAccount:
      create: true
      annotations: {}
      name: "codefresh-tunnel-router"
    
    replicaCount: 2
    
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podSecurityContext: {}
    podAnnotations: {}