{{/*
Config
*/}}
{{- define "codefresh-tunnel-client.config" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: codefresh-tunnel-client-config
  labels:
    {{- include "codefresh-tunnel-client.labels" . | nindent 4 }}
data:
  frpc.ini: |-
    [common]
    server_addr = {{ required "tunnelServer.host is required" .Values.tunnelServer.host }}
    server_port = {{ required "tunnelServer.port is required" .Values.tunnelServer.port }}
    log_level = {{ default "info" .Values.logLevel }}
    tls_enable = {{ default "true" .Values.tunnelServer.tls }}
    tls_trusted_ca_file = /etc/ssl/certs/ca-certificates.crt
    disable_custom_tls_first_byte = true
    protocol = {{ default "wss" .Values.tunnelServer.protocol }}
    admin_addr = 127.0.0.1
    admin_port = 7400
    admin_user = admin
    admin_pwd = admin
    [{{ required "tunnel.subdomainPrefix is required" .Values.tunnel.subdomainPrefix }}]
    type = {{ default "http" .Values.tunnel.forwardTo.type }}
    local_ip = {{ required "tunnel.forwardTo.host is required" .Values.tunnel.forwardTo.host }}
    local_port = {{ required "tunnel.forwardTo.port is required" .Values.tunnel.forwardTo.port }}
    locations = {{ default "/" .Values.tunnel.forwardTo.location }}
    subdomain = {{ .Values.tunnel.subdomainPrefix }}
    meta_Authorization = {{"{{"}} .Envs.AUTHORIZATION {{"}}"}}
    ips_allow_list = {{ default "" .Values.tunnel.ipsAllowList }}
{{- end }}