apiVersion: v1
kind: ConfigMap
metadata:
  name: codefresh-tunnel-server-config
data:
  frps.ini: |-
    [common]
    bind_port = 80
    vhost_http_port = 80
    subdomain_host = {{ .Values.tunnels.subdomainHost }}
    dashboard_port = 7500
    dashboard_user = admin
    dashboard_pwd = admin
    log_level = trace
