{{- if (include "codefresh-tunnel-server.tunnels.createTlsSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codefresh-tunnel-server.tunnels.tlsSecretName" . }}
  labels:
    {{- include "codefresh-tunnel-server.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  {{- $tls := buildCustomCert (required "A valid .Values.tunnels.ingress.tls.cert is required!" .Values.tunnels.ingress.tls.cert) (required "A valid .Values.tunnels.ingress.tls.key is required!" .Values.tunnels.ingress.tls.key) }}
  tls.crt: {{ b64enc $tls.Cert }}
  tls.key: {{ b64enc $tls.Key }}
{{- end }}