apiVersion: v1
kind: Service
metadata:
  name: {{ include "codefresh-tunnel-server.name" . }}
  labels:
    {{- include "codefresh-tunnel-server.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.service.annotations -}}
  {{ . | toYaml | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: server
    targetPort: 8080
    protocol: TCP
    port: 8080
  - name: dashboard
    targetPort: 7500
    protocol: TCP
    port: 7500
  selector:
    {{- include "codefresh-tunnel-server.selectorLabels" . | nindent 4 }}